version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Upgrading pip..."
      - pip3 install --upgrade pip3
      - echo "Installing zip..."
  build:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt
      - echo "Zipping Python dependencies as Lambda layer..."
      - python3 server.py
artifacts:
  files:
    - '**/*'
